version: "3.1"

services:

  wp:
    image: wordpress:${WP_CORE_VERSION}-php${PHP_VERSION}-apache
    container_name: ${PROJECT_NAME}_${VERSION_ID}_wp
    ports:
      - ${WEB_PORT_EXPOSED}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      WORDPRESS_DEBUG: 1
    volumes:
      - wp:/var/www/html # use docker volumes (view volumes below)
      # - ./wp:/var/www/html # use local path (view volumes below)
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: ${PROJECT_NAME}_${VERSION_ID}_db
    ports:
      - ${DB_PORT_EXPOSED}:3306
    volumes:
      - db:/var/lib/mysql
      - ./db.init:/docker-entrypoint-initdb.d
      - ./db.backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server port
      - 8025:8025 # web ui port

volumes:
  wp: # comment or local path or uncomment if you want use wp docker volumes 
  db:
